apiVersion: v1
kind: PersistentVolume
metadata:
  name: komga-books-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-server.nas.svc.cluster.local##komga-books
    volumeAttributes:
      server: nfs-server.nas.svc.cluster.local
      share: /books  # maps to /mnt/obj-storage/media/books on HDD
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-books-pvc
  namespace: komga
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: komga-books-pv
  resources:
    requests:
      storage: 25Gi
