apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata: 
  name: gpu-operator
  namespace: kube-system
spec:
  repo: https://helm.ngc.nvidia.com/nvidia
  chart: gpu-operator
  targetNamespace: gpu-operator
  valuesContent: |-
    operator:
      defaultRuntime: containerd
    driver:
      enabled: false  # Disable NVIDIA driver daemonset since there is error pulling image.
                      # On main machine we already install nvidia open so this should'nt poses any issue
      