apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata: 
  name: gpu-operator
  namespace: kube-system
spec:
  repo: https://helm.ngc.nvidia.com/nvidia
  chart: gpu-operator
  targetNamespace: gpu-operator
  valuesContent: |-
    operator:
      defaultRuntime: containerd
