apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-nas
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-server.nas.svc.cluster.local##
    volumeAttributes:
      server: nfs-server.nas.svc.cluster.local
      share: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-nas
  namespace: common
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: filebrowser-nas
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
  namespace: common
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
