apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-nas
  namespace: common
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Mi  # nominal — actual size is the full NFS share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
  namespace: common
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
