apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    ingress:
      - hostname: minecraft.haziqhakimi.online
        service: tcp://minecraft-service.minecraft.svc.cluster.local:25565
        originRequest:
          proxyType: socks
      - service: http_status:404