apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    # NOTE: This config is ignored for token-based tunnels
    # Tunnel config is managed via Cloudflare API
    # See bootstrap/apply-cloudflare-config.sh
    warp-routing:
      enabled: true
    # Below will get ignore
    ingress:
      - hostname: minecraft.haziqhakimi.online
        service: tcp://minecraft-service.minecraft.svc.cluster.local:25565
      - service: http_status:404