apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgresql-pvc.yaml
  - server-deployment.yaml
  - worker-deployment.yaml
  - rbac.yaml
  - ingress.yaml
