apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  capacity:
    storage: 355Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/obj-storage/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - haziq-homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: plex-media-pv
  resources:
    requests:
      storage: 355Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/obj-storage/plex-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - haziq-homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: plex-config-pv
  resources:
    requests:
      storage: 10Gi