apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: spark-operator
  namespace: kube-system
spec:
  repo: https://kubeflow.github.io/spark-operator
  chart: spark-operator
  targetNamespace: spark-operator
  valuesContent: |-
    controller:
      namespaces:
        - default
        - spark
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "500m"