apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: spark-operator
  namespace: kube-system
spec:
  repo: https://kubeflow.github.io/spark-operator
  chart: spark-operator
  targetNamespace: spark-operator
  valuesContent: |-
    controller:
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"