apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: kube-system
spec:
  repo: https://immich-app.github.io/immich-charts
  chart: immich
  targetNamespace: immich
  valuesContent: |-
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.1.0
            env:
              DB_HOSTNAME: immich-postgres.immich.svc.cluster.local
              DB_PORT: "5432"
              DB_USERNAME: immich
              DB_PASSWORD: immich
              DB_DATABASE_NAME: immich

    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc

    valkey:
      enabled: true
      persistence:
        data:
          type: emptyDir

    server:
      nodeSelector:
        kubernetes.io/hostname: haziq-homelab
      persistence:
        media:
          enabled: true
          existingClaim: immich-media-pvc
          advancedMounts:
            main:
              main:
                - path: /mnt/media
                  readOnly: true

    machine-learning:
      enabled: true
      nodeSelector:
        kubernetes.io/hostname: haziq-homelab
      controllers:
        main:
          pod:
            runtimeClassName: nvidia
          containers:
            main:
              image:
                tag: v3.1.0-cuda
              resources:
                limits:
                  nvidia.com/gpu: 1
              probes:
                startup:
                  spec:
                    failureThreshold: 60
                    periodSeconds: 10
      persistence:
        cache:
          storageClass: local-path
          size: 10Gi
