apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: kube-system
spec:
  repo: https://immich-app.github.io/immich-charts
  chart: immich
  targetNamespace: immich
  valuesContent: |-
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
    server:
      nodeSelector:
        kubernetes.io/hostname: haziq-homelab
      env:
        DB_HOSTNAME: immich-postgres.immich.svc.cluster.local
        DB_PORT: "5432"
        DB_USERNAME: immich
        DB_PASSWORD: immich
        DB_DATABASE_NAME: immich
        REDIS_HOSTNAME: immich-redis.immich.svc.cluster.local
        REDIS_PORT: "6379"
      extraVolumes:
        - name: media
          persistentVolumeClaim:
            claimName: immich-media-pvc
      extraVolumeMounts:
        - name: media
          mountPath: /mnt/media
          readOnly: true

    machine-learning:
      enabled: true
      nodeSelector:
        kubernetes.io/hostname: haziq-homelab
      runtimeClassName: nvidia
      resources:
        limits:
          nvidia.com/gpu: 1
      persistence:
        cache:
          storageClass: local-path
          size: 10Gi

